### ISSUE TITLE
Virtus + Factory Girl = trouble

### ISSUE THREAD

**Issue by GreenFomo** [solnic/virtus#231]
I'm using Virtus and it works great for what I need, but it somehow interferes with FactoryGirl when creating objects for rspecs..

Simply including Virtus.model into a model and trying to create an instance of it using FactoryGirl.create crashes spectacularly.. 

Here's the full stacktrace: 

```
←[K  1) V1::ShopsController Example test Should work
     Failure/Error: @shop = create(:shop)
     NoMethodError:
       undefined method `delete' for nil:NilClass
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/write.rb:37:in `write_attribute'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:70:in `write_attribute'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/write.rb:19:in `__temp__e616d656='
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:126:in `method_missing'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # H:in `object'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/factory.rb:42:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:161:in `instrument'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/factory_girl-4.3.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_m
ethod'
     # ./spec/controllers/v1/shops_controller_spec.rb:187:in `block (3 levels) in <top (required)>'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:237:in `instance_eval'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:237:in `instance_eval'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:21:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `block in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `each'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:446:in `run_hook'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:345:in `run_before_each_hooks'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:294:in `run_before_each'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:113:in `block in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:106:in `block (2 levels) in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:179:in `call'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:179:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:247:in `instance_eval_with_args'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:106:in `block (2 levels) in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:108:in `call'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:108:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:446:in `run_hook'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:340:in `run_around_each_hooks'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:256:in `with_around_each_hooks'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:111:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `map'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `run_examples'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:371:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `block in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `map'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `map'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block in run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/reporter.rb:58:in `report'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:25:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
     # H:/_work/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
```

From what I could glean by browsing through the source code of ActiveRecord (4.0), the @attributes_cache hash isn't initialized.. the initialization happens in a method called init_internals (in file core.rb of AR), which in turn is called in initialize (and some other places).. 

For whatever reason, when including Virtus.model, this "process" is skipped and that hash (and some others) are nil, therefore leading to this error.

Once again, this works fine when calling from a controller, it's creating with FactoryGirl that causes the issue.

Any idea about this behavior? Been pulling my hairs for the past few days over this.. 

Let me know if you need other details!

Thanks a lot in advance!

**Comment by ehwinter** [comment]
@solnic fyi I ran into the same issue  but for a different reason.  I think this could be avoided by making the guidance in README under *Embedded Value* more explicit. I (now) assume the only objects that can be embedded are either
 * ruby core classes: Hash, Array, String,...
 * Virtus classes
 * but *not* AR or Mongoid classes
```
class AssignmentSummary
  include Virtus.model
  attribute :date,           Date, default: nil
  attribute :league,         Organization, default: nil # a Mongoid class
```
The above seemed to work fine and I liked that the contract was explicitly stated. The issue arose only with FactoryGirl instantiating an entirely different class Venue(Mongoid) that did not utilize either AssignmentSummary(Virtus) or Organization(Mongoid). The fact that this issue arose in an entirely different, seemingly unrelated class was most curious.

My solution was:
```
class AssignmentSummary
  include Virtus.model
  attribute :date,           Date, default: nil
  attribute :league,         Object, default: nil 
  def valid?
    league.kind_of? League 
  end
```
I probably could have created a Virtus class wrapping League, but this was my simple solution.

**Comment by dkniffin** [comment]
Fyi for anyone having issues with factory_girl and virtus, #271 is related.
