### ISSUE TITLE
opaque error message

### ISSUE THREAD

**Issue by mattyb** [solnic/virtus#323]
initialization can fail with an opaque error message

```
     ArgumentError:
       struct size differs
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute/embedded_value.rb:20:in `initialize'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute/embedded_value.rb:20:in `new'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute/embedded_value.rb:20:in `call'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute.rb:103:in `coerce'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute/coercible.rb:14:in `set'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute_set.rb:146:in `block in define_writer_method'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute_set.rb:173:in `block in set'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute_set.rb:170:in `each'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/attribute_set.rb:170:in `set'
     # ~/.rvm/gems/ruby-2.2.2/gems/virtus-1.0.3/lib/virtus/instance_methods.rb:17:in `initialize'
```

**Comment by mikepence** [comment]
+1 Saw this fail on ruby 2.2.4 whereas it works correctly on 2.1.8
